Table users {
  id int [pk]
  email varchar [not null, unique]
  first_name varchar [not null]
  last_name varchar
  password varchar [not null]
  created_at datetime [default: `now()`]
}

Table quotes {
  id int [pk]
  code varchar(15) [not null, unique]
  high float [not null]
  low float [not null]
  varBid float [not null]
  pctChange float [not null]
  bid float [not null]
  ask float [not null]
}

Table accounts {
  id int [pk]
  name varchar [not null, unique]
  balance float [not null, unique]
  account_holder_id int [ref: > users.id]

  indexes {
    (account_holder_id, name) [unique]
  }
}