"""add color column in accounts table

Revision ID: 35657b487b85
Revises: 190fd9bdf11e
Create Date: 2025-08-06 14:42:21.591553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35657b487b85'
down_revision: Union[str, Sequence[str], None] = '190fd9bdf11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('color', sa.String(length=7), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'color')
    # ### end Alembic commands ###
